---
- name: download td-agent install script
  get_url: url=https://td-toolbelt.herokuapp.com/sh/install-redhat-td-agent2.sh dest=/tmp/install-td-agent.sh

- name: execute install script
  sudo: yes
  command: sh /tmp/install-td-agent.sh

- name: Place config files
  sudo: yes
  template: src=td-agent.conf.j2 dest=/etc/td-agent/td-agent.conf

- name: start td-agent
  sudo: yes
  service: name=td-agent state=restarted enabled=yes
