---
- name: Install common pkgs
  sudo: yes
  yum: pkg={{item}} state=present
  with_items:
    - epel-release
    - cronie

- name: Enable crond
  sudo: yes
  shell: systemctl start crond && systemctl enable crond

- name: Create www dir
  sudo: yes
  file: path=/var/www state=directory

- name: Create app root
  sudo: yes
  file: path={{ app_root }} state=directory owner={{ os_user }}

- name: Check to see if selinux exists
  stat: path=/etc/selinux/config
  register: selinux_conf

- name: Edit SELinux Config file
  sudo: yes
  lineinfile: dest=/etc/selinux/config regexp=^SELINUX= line=SELINUX=permissive
  when: selinux_conf.stat.exists == True

- name: Disable SELinux
  sudo: yes
  command: setenforce 0
  when: selinux_conf.stat.exists == True
