---
- name: Install dependencies
  sudo: yes
  yum: pkg={{item}} state=present
  with_items:
    - git
    - tar
    - gcc
    - make
    - libffi-devel
    - zlib-devel
    - openssl-devel
    - ruby

- name: Install rbenv
  sudo: yes
  git: repo=https://github.com/sstephenson/rbenv.git dest={{ rbenv.root_path }}

- name: Install ruby-build
  sudo: yes
  git: repo=https://github.com/sstephenson/ruby-build.git dest={{ rbenv.root_path }}/plugins/ruby-build

- name: Install rbenv-gem-rehash
  sudo: yes
  git: repo=https://github.com/sstephenson/rbenv-gem-rehash.git dest={{ rbenv.root_path }}/plugins/rbenv-gem-rehash

- name: create rbenv group
  sudo: yes
  group: name=rbenv state=present

- name: add user to rbenv group
  sudo: yes
  user: name=centos append=yes groups=rbenv

- name: create shims dir
  sudo: yes
  file: path={{ rbenv.root_path }}/shims state=directory

- name: create versions dir
  sudo: yes
  file: path={{ rbenv.root_path }}/versions state=directory

- name: change owner of install dir
  sudo: yes
  command: chgrp -R rbenv {{ rbenv.root_path }}

- name: change mode of install dir
  sudo: yes
  command: chmod -R g+rwxXs {{ rbenv.root_path }}

- name: Set rbenv env file
  sudo: yes
  copy: src=rbenv.sh dest=/etc/profile.d mode=0775

- name: Install ruby with rbenv
  shell: bash -lc 'CONFIGURE_OPTS="--disable-install-rdoc" rbenv install {{ rbenv.ruby_version }} -s'

- name: "set ruby to {{ rbenv.ruby_version }} as global scope"
  shell: bash -lc "rbenv global {{ rbenv.ruby_version }} && gem install bundler --no-ri --no-rdoc && rbenv rehash"
